# -*- coding: utf-8 -*-
"""Encora Jesús Eduardo Valenzuela.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jdxz3Gje1ox8vzHkPSIysRLtj1Q2JURq

**Ejercicio**
"""

#Para este programa asumiré que:
  #1.- No se puede entrar en una ronda ya iniciada
  #2.- No se puede salir una vez la ronda inicie, debe estar dentro del juego hasta el final
  #Por lo que el programa calcula la cantidad de rondas COMPLETAS que se jugaron


hora_inicio = str(input("Hora de inicio en fornato HH:MM ")) #entrada de la hora de inicio
hora_final = str(input("Hora de terminación en formato HH:MM ")) #entrada de la hora final
hora_a="" #string donde se almacenarán los dos caracteres de la hora de inicio
hora_b="" #string donde se almacenarán los dos caracteres de la hora final
minutos_a="" #string donde se almacenarán los dos caracteres de los minutos de la hora de inicio
minutos_b=""#string donde se almacenarán los dos caracteres de los miutos de la hora final
horas_dia = 24*60

#Estos loops se encargaron de la asignación de caracteres a las variables previamente mencionadas
for i in range(0,2):
  hora_a= hora_a + hora_inicio[i]
  hora_b= hora_b + hora_final[i]
hora_a , hora_b = int(hora_a), int(hora_b)
for j in range(3,5):
  minutos_a=minutos_a+hora_inicio[j]
  minutos_b=minutos_b+hora_final[j]
minutos_a, minutos_b = int(minutos_a) , int(minutos_b)



#Condiciones para los minutos en la hora de inicio, poniendo en sí, el verdadero tiempo en minutos en el que inició una partida
#De esta manera en caso de que se conecte y tenga que esperar una partida, tomará en cuenta como si se hubiese conectado exactamente a la 
#hora de inicio de la partida próxima
if minutos_a > 0 and minutos_a <= 15: 
  minutos_a = 15
elif minutos_a > 15 and minutos_a <=30:
  minutos_a = 30
elif minutos_a > 30 and minutos_a <=45:
  minutos_a = 45
else:
  minutos_a = 0


#Condiciones para los minutos en la hora de terminación, poniendo en sí, el verdadero tiempo en minutos en el que terminó una partida
#Como en el caso anterior, solo que asegurando de que juegue solo partidas completas, si se desconecta en medio de una partida, no cuenta
#en el conteo
if minutos_b > 0 and minutos_b <= 15:
  minutos_b = 0
elif minutos_b > 15 and minutos_b <=30:
  minutos_b = 15
elif minutos_b > 30 and minutos_b <=45:
  minutos_b = 30
else:
  minutos_b = 45

#Horas reseteadas
  
print("La verdadera hora de inicio de ronda es: ",hora_a,":",minutos_a) 
print("La verdadera hora de conclusión de la ultima ronda es ",hora_b,":",minutos_b)



#Conversión de horas a minutos
hora_a = hora_a*60
hora_b = hora_b*60

#Diferencia de tiempos en minutos
tiempo_a = hora_a + minutos_a
tiempo_b = hora_b + minutos_b

#Para asegurar el orden de diferencias
if tiempo_a > tiempo_b:
  diferencia_tiempo = horas_dia - (tiempo_a - tiempo_b)
elif tiempo_a == tiempo_b:
  diferencia_tiempo = 0
else:
  diferencia_tiempo = tiempo_b - tiempo_a

#Calculo de rondas jugadas
rondas_jugadas = diferencia_tiempo/15
print("El numero total de rondas jugadas es: ",rondas_jugadas)

